name: Delete Production Environment

permissions:
  id-token: write

on:
  workflow_dispatch

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  
  delete_env:
    runs-on: ubuntu-latest
    environment: Production

    env:
      ENVIRONMENT_NAME: "ci-branch-main-682042278"
      ENVIRONMENT_TYPE: "Production"

    steps:
      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Delete Environment
        run: |
          az devcenter dev environment delete --name ${{ env.ENVIRONMENT_NAME }} \
              --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} --yes
