name: Delete Environment tmp

permissions:
  id-token: write

on:
  workflow_dispatch


jobs:
  
  delete_env:
   
    runs-on: ubuntu-latest

    
    

    steps:
      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Delete Environment
        run: |
          az devcenter dev environment delete --environment-name ci-branch-main-682042278 --project devcenter-demo --dev-center-name azh-devcenter --yes